# Generated by Django 2.0.4 on 2018-05-16 14:31

import app.site_mgt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_name', models.CharField(default='SERVE ESTATE', max_length=300)),
                ('estate_address', models.CharField(default='14a, sasegbon Ikeja GRA', max_length=500)),
                ('estate_logo', models.ImageField(blank=True, null=True, upload_to=app.site_mgt.models.upload_path)),
            ],
            options={
                'verbose_name': 'Estate Detail',
                'verbose_name_plural': 'Estate Detail',
            },
        ),
    ]
