# Generated by Django 2.0.5 on 2018-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180723_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_status',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
