# Generated by Django 2.0.4 on 2018-05-16 14:31

import app.estate_mgt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('estate_id', models.CharField(default=app.estate_mgt.models.estate_id, max_length=30, primary_key=True, serialize=False)),
                ('estate_name', models.CharField(max_length=200)),
                ('estate_address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
