# Generated by Django 2.0.5 on 2018-07-23 07:24

import app.estate_mgt.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartment_id', models.CharField(default=app.estate_mgt.models.estate_id, max_length=30, primary_key=True, serialize=False)),
                ('apartment_number', models.CharField(max_length=250, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(default=app.estate_mgt.models.estate_id, max_length=30, primary_key=True, serialize=False)),
                ('building_number', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salutation',
            fields=[
                ('title_id', models.CharField(default=app.estate_mgt.models.estate_id, max_length=30, primary_key=True, serialize=False)),
                ('title_name', models.CharField(max_length=250, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('street_id', models.CharField(default=app.estate_mgt.models.estate_id, max_length=30, primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=250, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_mgt.Estate')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_mgt.Street'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_mgt.Building'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_mgt.Street'),
        ),
    ]
