# Generated by Django 2.0.5 on 2018-07-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0002_auto_20180723_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='building',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='street',
        ),
        migrations.RemoveField(
            model_name='building',
            name='street',
        ),
        migrations.DeleteModel(
            name='Salutation',
        ),
        migrations.RemoveField(
            model_name='street',
            name='estate',
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
