# Generated by Django 2.0.5 on 2018-07-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_mgt', '0004_auto_20180723_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='street',
            name='street_name',
            field=models.CharField(max_length=250),
        ),
    ]
