# Generated by Django 2.0.4 on 2018-05-16 14:53

import app.vistor_mgt.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVistor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistor_first_name', models.CharField(max_length=120, null=True)),
                ('vistor_last_name', models.CharField(max_length=120, null=True)),
                ('vistor_mobile_number', models.BigIntegerField()),
                ('vistor_unique_code', models.CharField(default=app.vistor_mgt.models.unique_code, max_length=6)),
                ('unique_code_is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_out', models.BooleanField(default=False)),
                ('checked_in_date', models.DateTimeField(blank=True)),
                ('checked_out_date', models.DateTimeField(blank=True)),
                ('estate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate_mgt.Estate')),
                ('whom_to_see', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
