# Generated by Django 2.0.5 on 2018-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistor_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvistor',
            name='checked_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newvistor',
            name='checked_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
